background {
  monitor = # monitor-agnostic
  path =/usr/share/hypr/cat.jpg
#  blur_passes = 1
#  blur_size = 1
}

input-field {
  monitor =
  size = 20%, 5%
  font_family = Noto Sans
  dots_size = 0.20
}

label {
  monitor =
  text = $TIME
  font_size = 100
  position = 0, -80
}
